# Generated by Django 2.2.1 on 2019-07-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20190717_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=5),
        ),
    ]
